# Generated by Django 5.1.4 on 2025-01-20 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_options_todo_created_todo_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=200)),
                ('course_instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('slot', models.CharField(blank=True, choices=[('1A', '1A - Monday 08:30-09:25'), ('2A', '2A - Monday 09:30-10:25'), ('3A', '3A - Monday 10:35-11:30'), ('4A', '4A - Monday 11:35-12:30'), ('8A', '8A - Monday 02:00-03:25'), ('9A', '9A - Monday 03:30-04:55'), ('12A', '12A - Monday 05:30-06:55'), ('13A', '13A - Monday 07:00-08:25'), ('4B', '4B - Tuesday 08:30-09:25'), ('1B', '1B - Tuesday 09:30-10:25'), ('2B', '2B - Tuesday 10:35-11:30'), ('3B', '3B - Tuesday 11:35-12:30'), ('10A', '10A - Tuesday 02:00-03:25'), ('11A', '11A - Tuesday 03:30-04:55'), ('14A', '14A - Tuesday 05:30-06:55'), ('15A', '15A - Tuesday 07:00-08:25'), ('7A', '7A - Wednesday 08:30-09:25'), ('5A', '5A - Wednesday 09:30-10:55'), ('6A', '6A - Wednesday 11:05-12:30'), ('X1', 'X1 - Wednesday 02:00-03:00'), ('X2', 'X2 - Wednesday 03:00-04:00'), ('X3', 'X3 - Wednesday 04:00-05:00'), ('XC', 'XC - Wednesday 05:30-06:55'), ('XD', 'XD - Wednesday 07:00-08:25'), ('3C', '3C - Thursday 08:30-09:25'), ('4C', '4C - Thursday 09:30-10:25'), ('1C', '1C - Thursday 10:35-11:30'), ('2C', '2C - Thursday 11:35-12:30'), ('8B', '8B - Thursday 02:00-03:25'), ('9B', '9B - Thursday 03:30-04:55'), ('12B', '12B - Thursday 05:30-06:55'), ('13B', '13B - Thursday 07:00-08:25'), ('7B', '7B - Friday 08:30-09:25'), ('5B', '5B - Friday 09:30-10:55'), ('6B', '6B - Friday 11:05-12:30'), ('10B', '10B - Friday 02:00-03:25'), ('11B', '11B - Friday 03:30-04:55'), ('14B', '14B - Friday 05:30-06:55'), ('15B', '15B - Friday 07:00-08:25'), ('L1', 'Lab 1 - Monday 02:00-04:55'), ('L2', 'Lab 2 - Tuesday 02:00-04:55'), ('L3', 'Lab 3 - Thursday 02:00-04:55'), ('L4', 'Lab 4 - Friday 02:00-04:55'), ('L5', 'Lab 5 - Wednesday Morning'), ('L6', 'Lab 6 - Friday Morning'), ('LX', 'Lab X - Wednesday Afternoon')], max_length=200, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=200, null=True)),
                ('slot', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
